# Generated by Django 5.2.3 on 2025-06-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_serviceproviderprofile_service_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Provider's price for their service", max_digits=10, null=True),
        ),
    ]
